INSERT INTO
    treehousedb.acessos_ids (acesso_nome)
VALUES
    ('Gerente Sistema'), ('Gerente Organização'), ('Professor'), ('Assistente Sistema');


insert into
    treehousedb.usuarios (nome_usuario, email_usuario, senha, id_acesso, id_funcao, cpf, rg, celular, data_nascimento)
VALUES
    ('Bruno Quoos', 'bruno@treehouse.com', '123456789', 1, 0, '0000000000', '00000000000', '43996630496', '2023-12-06');


INSERT INTO treehousedb.profesoras (nome) VALUES
                                              ('Bruno Schmaiske Quoos'),
                                              ('Luana Rodrigues Quoos'),
                                              ('Liohana Gaspar da Silva'),
                                              ('Jéssica Andressa da Costa Machado'),
                                              ('Raphaela Mykytzczuk De Matos'),
                                              ('Yasmin Grummt Naddaf'),
                                              ('Maria Fernanda'),
                                              ('Emanuelle Maciel'),
                                              ('Luana Maria Figueiredo Salviano Pallaro'),
                                              ('Ana Luiza Egg');

INSERT INTO treehousedb.turmas (nome_turma) VALUES
                                    ('teste 1'),
                                    ('teste 2'),
                                    ('teste 3'),
                                    ('teste 4'),
                                    ('teste 5'),
                                    ('teste 6'),
                                    ('teste 7'),
                                    ('teste 8'),
                                    ('teste 9'),
                                    ('teste 10');


INSERT INTO treehousedb.alunos (nome) VALUES
                              ('TreeHouse'),
                              ('Max Roda Lopes'),
                              ('Miguel Zipf Fabri'),
                              ('Clara Zipf Fabri'),
                              ('Manuela Fontoura De Souza'),
                              ('Pedro Carneiro Akiyama'),
                              ('Mario Grynbaum & Rodrigo Grynbaum'),
                              ('Rodrigo Grynbaum'),
                              ('Gabriela De Pauli Kinaki'),
                              ('Rafael Dall Acqua Winter'),
                              ('Valentina paulino Tareszkiewicz'),
                              ('Paola Carneiro Akiyama'),
                              ('Helena Longo De Camargo'),
                              ('Luigi Scheinkman'),
                              ('Luisa De Pauli Kinaki'),
                              ('Daniel Longo De Camargo'),
                              ('Leandro Scheinkman De Souza'),
                              ('Martina Pozzobon Lara dos Santos'),
                              ('Sophia Fernandes Rodrigues'),
                              ('Maria Luísa Komuchena Malinoski'),
                              ('Maria Cecília Komuchena Malinoski'),
                              ('Maria Teresa Komuchena Malinoski'),
                              ('Bernardo Amin Bacila'),
                              ('Leticia Belich'),
                              ('Luciane & Ane'),
                              ('Violeta Chalegre Sens'),
                              ('Matheus César Chalegre Sens'),
                              ('Dhara Husseini'),
                              ('Lorenzo Vecchi Pinheiro'),
                              ('Estela do Nascimento Cardoso'),
                              ('Helena Navachi Paúra'),
                              ('Luca Gauer Marchini & Bianca Gauer Marchini'),
                              ('Heloisa da Silveira Colares'),
                              ('Felipe da Silveira Colares'),
                              ('Antonella Gonçalves Machado'),
                              ('Vicenzo Sarolli Busato'),
                              ('Kambalhota Educação Infantil'),
                              ('Julia Weinert de Andrade'),
                              ('Escola Israelita'),
                              ('Vila Sofia'),
                              ('Francisco Paulino Tareszkiewicz'),
                              ('Diana dos Santos Pellanda'),
                              ('Mariana Zortea Tauchmann'),
                              ('Fernanda Zortea Tauchmann'),
                              ('Ruan Rossi'),
                              ('Ísis Passere Zamblauskas'),
                              ('Angelina Sarolli Busato'),
                              ('Lindsey Helena Ferreira Cordeiro'),
                              ('Beatriz Kempinski amorim'),
                              ('Sophia França Costa da Silva'),
                              ('Nathan Boiko'),
                              ('Thaís, Paula  e Laura Seleme de Campos'),
                              ('Davi de Mello Norte'),
                              ('Luigi cima'),
                              ('Laura Dubas Matocheck'),
                              ('Alicia Ferreira Setim'),
                              ('Valentina Sperandio Daleffe'),
                              ('Flávia Bomfim Milek'),
                              ('Escola Kids'),
                              ('Daniel ruggi fatiga'),
                              ('Beatriz ruggi fatiga'),
                              ('Arthur fisbein Katz'),
                              ('Gabriel Favaretto ruppel'),
                              ('Vítor Cristofolini Meretika'),
                              ('Valentina Fressato Esteves'),
                              ('Maitê Monteiro Casagrande'),
                              ('Benjamin Monteiro Casagrande'),
                              ('Pedro Thoaldo Canteri'),
                              ('Ayla Ferraz Novak'),
                              ('João Paulo Mendes Lima');


INSERT INTO treehousedb.alunos_turmas (id_aluno, id_turma) VALUES
                                                               (1, 1),
                                                               (2, 2),
                                                               (3, 3),
                                                               (4, 4),
                                                               (5, 5),
                                                               (6, 6),
                                                               (7, 7),
                                                               (8, 8),
                                                               (9, 9),
                                                               (10, 10),
                                                               (11, 1),
                                                               (12, 2),
                                                               (13, 3),
                                                               (14, 4),
                                                               (15, 5),
                                                               (16, 6),
                                                               (17, 7),
                                                               (18, 8),
                                                               (19, 9),
                                                               (20, 10),
                                                               (21, 1),
                                                               (22, 2),
                                                               (23, 3),
                                                               (24, 4),
                                                               (25, 5),
                                                               (26, 6),
                                                               (27, 7),
                                                               (28, 8),
                                                               (29, 9),
                                                               (30, 10),
                                                               (31, 1),
                                                               (32, 2),
                                                               (33, 3),
                                                               (34, 4),
                                                               (35, 5),
                                                               (36, 6),
                                                               (37, 7),
                                                               (38, 8),
                                                               (39, 9),
                                                               (40, 10),
                                                               (41, 1),
                                                               (42, 2),
                                                               (43, 3),
                                                               (44, 4),
                                                               (45, 5),
                                                               (46, 6),
                                                               (47, 7),
                                                               (48, 8),
                                                               (49, 9),
                                                               (50, 10),
                                                               (51, 1),
                                                               (52, 2),
                                                               (53, 3),
                                                               (54, 4),
                                                               (55, 5),
                                                               (56, 6),
                                                               (57, 7),
                                                               (58, 8),
                                                               (59, 9),
                                                               (60, 10),
                                                               (61, 1),
                                                               (62, 2),
                                                               (63, 3),
                                                               (64, 4),
                                                               (65, 5),
                                                               (66, 6),
                                                               (67, 7),
                                                               (68, 8),
                                                               (69, 9),
                                                               (70, 10);


-- Inserting 50 random entries with specific time slots
SET @start_date = '2023-12-01';
SET @end_date = '2023-12-10';

INSERT INTO treehousedb.aulas (datahora_aula, datahora_fim_aula, id_turma, id_status_aula)
VALUES
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 10:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 11:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 13:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 14:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 10:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 11:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 13:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 14:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 10:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 11:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 13:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 14:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 10:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 11:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 13:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 14:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 10:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 11:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 13:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 14:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 10:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 11:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 13:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 14:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 10:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 11:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 13:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 14:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 10:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 11:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 13:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 14:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 10:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 11:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 13:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 14:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 10:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 11:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 13:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 14:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 10:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 11:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 13:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 14:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 10:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 11:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 13:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 14:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 10:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 11:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 13:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 14:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 10:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 11:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 13:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5)),
    (CONCAT(DATE_ADD(@start_date, INTERVAL FLOOR(RAND() * 10) DAY), ' 14:00:00'), NULL, FLOOR(1 + RAND() * 10), FLOOR(1 + RAND() * 5));


INSERT INTO treehousedb.alunos_aulas (id_aluno, id_aula, id_professor)
VALUES
    (6,6,1),
    (56,6,1),
    (36,6,1),
    (1,1,1),
    (11,1,1),
    (21,1,1),
    (31,1,1),
    (41,1,1);

